var envObj ={
    "prefix":"rio",
    "prefix_name":"risktech.io",
    "devops":"dev",
    "devops_name":"Development",
    "lane":"plg",
    "lane_name":"Playground",
    "step":"cod",
    "step_name":"CodeIntegration",
    "type":"wap",
    "type_name":"WebApplication",
    "appl":"pws",
    "appl_name":"ProjectWebSite",
    "speed":"mav",
    "speed_name":"MajorVersion",
    "region":"pri",
    "region_name":"Primary",
    "region_key": "SouthEastAsia",
    "slot": "green",
    "slot_name": "Green",
    "subscription_name": "rio-dev-plg-cod-wap-pws-s",
    "subscription_id": "0df8df1d-d4e2-476e-8af1-5e0bccbe01f3",
    "webapp_resource_group":"rio-dev-plg-cod-wap-pws-mav-pri-grn-rg",
    "webapp_host":"rio-dev-plg-cod-wap-pws-mav-pri-grn-wap",
    "webapp_url":"rio-dev-plg-cod-wap-pws-mav-pri-grn-wap.azurewebsites.net",
    "webapp_url_custom":"rio-dev-plg-cod-wap-pws-mav-pri-grn-wap.azurewebsites.net",
    "branch":"dev/plg/cod/mav/grn",
    "tenant_name":"Together",
    "tenant_country":"Austria",
    "tenant_location": "EU Model Clause compliant datacenters",
    "tenant_id":"3e0b6cbd-4959-4d01-81bf-ce883ddabd96",
    "tenant_primary_domain":"together.at",
    "wap_client_id":"",
    "api_client_id":"",
    "api_resource_group":"rio-dev-plg-cod-adf-pws-mav-pri-grn-rg",
    "api_host":"rio-dev-plg-cod-adf-pws-mav-pri-grn-fap",
    "api_url":"rio-dev-plg-cod-adf-pws-mav-pri-grn-fap.azurewebsites.net",
    "api_url_custom":"rio-dev-plg-cod-adf-pws-mav-pri-grn-fap.azurewebsites.net",
    "subset":"",
    "build_vsts_orga":"",
    "build_vsts_project":"",
    "build_vsts_git":"",
    "build_vsts_branch":"",
    "sources_branch":"",
    "branding_vsts_orga":"",
    "branding_vsts_project":"",
    "branding_vsts_git":"",
    "branding_vsts_branch":"",
    "organization": "risktech-io",
    "organization_name": "risktech.io",
    "project": "rio-app-pws",
    "project_name":"Project WebSite",
    "project_prefix":"rio",
    "project_type":"app",
    "project_keyvalue": "pws",
    "git": "rio-wap-pws",
    "git_prefix:": "rio",
    "git_type:": "wap",
    "git_keyvalue:": "pws",
    "version_major":"1"
  }