var projObj = {
  "authors": [ "Together Teamsolutions Co., Ltd.", "GrECo JLT" ],
  "company": "Together Teamsolutions Co., Ltd.",
  "analytic_name":"Ing. Alfred Madl",
  "analytic_tel":"+43 5 0404 888",
  "analytic_mail":"a.madl@togetherteam.co.th",
  "developer_name":"Ing. Alfred Madl",
  "developer_tel":"+43 5 0404 888",
  "developer_mail":"a.madl@togetherteam.co.th",
  "project_mgr_name":"Ing. Alfred Madl",
  "project_mgr_tel":"+43 5 0404 888",
  "project_mgr_mail":"a.madl@togetherteam.co.th",
  "support_name":"Ing. Alfred Madl",
  "support_tel":"+43 5 0404 888",
  "support_mail":"a.madl@togetherteam.co.th",
  "language": "en_GB",
  "country":"Group",
  "priority":"3",
  "urgent":"false",
  "important":"false",
  "type":"System item",
  "subtype":"Documentation",
  "impact":"internal",
  "value":"Architecture",
  "origin":"New requirement",
  "phase":"4",
  "status":"Development",
  "business_area":"e.g. insurance line",
  "project": "rio-app-pws",
  "project_name": "risktech.io PWS",
  "project_prefix":"rio",
  "project_type":"app",
  "project_keyvalue": "pws",
  "organization": "risktech-io",
  "organization_name": "risktech.io",
  "git": "rio-wap-pws",
  "git_prefix:": "rio",
  "git_type:": "wap",
  "git_keyvalue:": "pws",
  "gits_other": ["rio-adf-pws", "rio-aim-pws"],
  "description": "Project WebSite",
  "copyright": "(c) 2018 Together Teamsolutions Co., Ltd.",
  "version_major": "1",
  "chapters":[{"name":"Icons", "link":"stat/v1/icons/README.md"}],
  "documents":[
    {"name":"IT-Dev Status 2017", "link":"https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Frio-dev-plg-cod-wap-pws-mav-pri-grn-wap.azurewebsites.net%2Fstat%2Fv1%2Fdoc%2F2017-ITDevStatusInklusiveInputMozelt.docx"},
    {"name":"Platform Evaluation", "link":"https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Frio-dev-plg-cod-wap-pws-mav-pri-grn-wap.azurewebsites.net%2Fstat%2Fv1%2Fdoc%2F2017-GOSAppPlatformEvaluation.docx"},
    {"name":"Project Definition", "link":"stat/v1/doc/2017-Projekt-risktech.io-V4-Vorstand.pdf"}
    ],
  "copyright":"(c) Copyright Together Teamsolutions Co., Ltd. - All rights reserved.",
  "templates":[{"path":"templ","templgroup":"foldernamegrp","templname":"foldernametempl", "templversion":"v1"}],
}