var headerObj = {
    "use graph proxy api": false,
    "use outlook settings": false,
    "use user property extensions": true,
    "app launcher": false,
    "environment": false,
    "notifications": false,
    "settings": true,
    "help": true,
    "account": true,
    "theme settings": true,
    "language settings": true,
    "time zone settings": true,
    "feedback": false,
    "feedbackurl": "",
    "feedbackmethod": "POST",
    "maximize": false,
    "mailbox photo": false,
    "themes": "./appcnfs/themes.json.js",
    "phraseapp": false,
    "phraseapp project id": "",
    "phraseapp prefix": "[[__",
    "phraseapp suffix": "__]]",
    "form width percent": "",
    "processtext": "Overridden text",
    "elearningtext": "",
    "autocalc": "",
    "updatecalcresult": true,
    "calc_js_path_local": "",
    "calc_js_path": "",
    "calc_js_setting": "",
    "calc_conf_path": "",
    "calc_conf_setting": "",
    "calc_api_path": "",
    "action":"Form('{formname}/{formversion}')/Submit",
    "action before script" : "",
    "action success script" : "",
    "action failure script" : "",
    "action local script" : "",
    "action graph proxy": "",
    "action loading":"Form('{formname}/{formversion}')/Loading",
    "action loaded":"Form('{formname}/{formversion}')/Loaded",
    "action focus":"Form('{formname}/{formversion}')/Focus",
    "action focus local script":"",
    "action blur":"Form('{formname}/{formversion}')/Blur",
    "action blur local script":"",
    "action change":"Form('{formname}/{formversion}')/Change",
    "action change local script":"",
    "action search":"Form('{formname}/{formversion}')/Search",
    "action search local script":"",
    "action showDropdown":"Form('{formname}/{formversion}')/ShowDropdown",
    "action showDropdown local script":"",
    "action click":"Form('{formname}/{formversion}')/Click",
    "action click local script":"",
    "action dblclick":"Form('{formname}/{formversion}')/DblClick",
    "action dblclick local script":"",
    "action contextMenu":"Form('{formname}/{formversion}')/ContextMenu",
    "action contextMenu local script":"",
    "action wheel":"Form('{formname}/{formversion}')/Wheel",
    "action wheel local script":"",
    "action mouseover":"Form('{formname}/{formversion}')/MouseOver",
    "action mouseover local script":"",
    "action mousedown":"Form('{formname}/{formversion}')/MouseDown",
    "action mousedown local script":"",
    "action mouseout":"Form('{formname}/{formversion}')/MouseOut",
    "action mouseout local script":"",
    "action mouseup":"Form('{formname}/{formversion}')/MouseUp",
    "action mouseup local script":"",
    "action mousemove":"Form('{formname}/{formversion}')/MouseMove",
    "action mousemove local script":"",
    "action mouseenter":"Form('{formname}/{formversion}')/MouseEnter",
    "action mouseenter local script":"",
    "action mouseleave":"Form('{formname}/{formversion}')/MouseLeave",
    "action mouseleave local script":"",
    "action keypress":"Form('{formname}/{formversion}')/KeyPress",
    "action keypress local script":"",
    "action keyup":"Form('{formname}/{formversion}')/KeyUp",
    "action keyup local script":"",
    "action keydown":"Form('{formname}/{formversion}')/KeyDown",
    "action keydown local script":"",
    "action input":"Form('{formname}/{formversion}')/Input",
    "action input local script":"",
    "action prevPage":"Form('{formname}/{formversion}')/PrevPage",
    "action prevPage local script":"",
    "action nextPage":"Form('{formname}/{formversion}')/NextPage",
    "action nextPage local script":"",
    "action componentError":"Form('{formname}/{formversion}')/ComponentError",
    "action componentError local script":"",
    "action beforeprint":"Form('{formname}/{formversion}')/BeforePrint",
    "action beforeprint local script":"",
    "action afterprint":"Form('{formname}/{formversion}')/AfterPrint",
    "action afterprint local script":"",
    "action resize":"Form('{formname}/{formversion}')/Resize",
    "action resize local script":"",
    "action select":"Form('{formname}/{formversion}')/Select",
    "action select local script":"",
    "action cut":"Form('{formname}/{formversion}')/Cut",
    "action cut local script":"",
    "action copy":"Form('{formname}/{formversion}')/Copy",
    "action copy local script":"",
    "action paste":"Form('{formname}/{formversion}')/Paste",
    "action paste local script":"",
    "action scroll":"Form('{formname}/{formversion}')/Scroll",
    "action scroll local script":"",
    "action dirty changed":"Form('{formname}/{formversion}')/DirtyChanged",
    "action dirty changed local script":"",
    "action wait calculation": false,
    "bing maps key": "",
    "map wrapper id": "",
    "map route info wrapper id": "",
    "map country name": "",
    "map zoom": "",
    "map center pushpin": true,
    "map center pushpin title": "",
    "map center pushpin subtitle": "",
    "map center pushpin description": "",
    "map center latitude": "",
    "map center longitude": "",
    "map show info box": true,
    "map show traffic": "",
    "toggle menu": true,
    "triggerResizeChange": true,
    "userlangs": "./defs/userlangs.json.js",
    "defaultLanguage": "en-GB",
    "timezones": "./defs/timezones.json.js",
    "defaultTimeZone": "UTC",
    "disableActionSpinner": false,
    "menus": "",
    "langmenustop": "",
    "langmenusbottom": "",
    "menuposition": "top",
    "menupositionthreshold": "",
    "test": true,
    "debug": true,
    "choicesOptions": "",
    "sendForm": false,
    "formtranslation": "",
    "additional api function resource": "",
    "additional api function url": "",
    "additional api function method": "",
    "additional api function payload": ""
};