var langObj = {
    i18n: {
        'bg-BG': {
            'The first number to add': 'Първо добавете',
            'The second number to add': 'Второ добавяне',
            'january': 'Януари',
            'february': 'Февруари',
            'march': 'Март',
            'april': 'Април',
            'may': 'Май',
            'june': 'Юни',
            'july': 'Юли',
            'august': 'Август',
            'september': 'Септември',
            'october': 'Октомври',
            'november': 'Ноември',
            'december': 'Декември'
        },
        'cs-CZ': {
            'january': 'leden',
            'february': 'únor',
            'march': 'březen',
            'april': 'duben',
            'may': 'květen',
            'june': 'červen',
            'july': 'červenec',
            'august': 'srpen',
            'september': 'září',
            'october': 'říjen',
            'november': 'listopad',
            'december': 'prosinec'
        },
        'de-AT': {
            'The first number to add': 'Erstes Summand',
            'The second number to add': 'Zweiter Summand',
            'january': 'Januar',
            'february': 'Februar',
            'march': 'März',
            'april': 'April',
            'may': 'Mai',
            'june': 'Juni',
            'july': 'Juli',
            'august': 'August',
            'september': 'September',
            'october': 'Oktober',
            'november': 'November',
            'december': 'December'
        },
        'et-EE': {
            'january': 'jaanuar',
            'february': 'veebruar',
            'march': 'märts',
            'april': 'aprill',
            'may': 'mai',
            'june': 'juuni',
            'july': 'juuli',
            'august': 'august',
            'september': 'september',
            'october': 'oktoober',
            'november': 'november',
            'december': 'detsember'
        },
        'en-GB': {
            'The first number to add': 'The first number to add',
            'The second number to add': 'The second number to add',
            'january': 'January',
            'february': 'February',
            'march': 'March',
            'april': 'April',
            'may': 'May',
            'june': 'June',
            'july': 'July',
            'august': 'August',
            'september': 'September',
            'october': 'October',
            'november': 'November',
            'december': 'December'
        },
        'hr-HR': {
            'january': 'siječanj',
            'february': 'veljača',
            'march': 'ožujak',
            'april': 'travanj',
            'may': 'svibanj',
            'june': 'lipanj',
            'july': 'srpanj',
            'august': 'kolovoz',
            'september': 'rujan',
            'october': 'listopad',
            'november': 'studeni',
            'december': 'prosinac'
        },
        'hu-HU': {
            'january': 'január',
            'february': 'február',
            'march': 'március',
            'april': 'április',
            'may': 'május',
            'june': 'június',
            'july': 'július',
            'august': 'augusztus',
            'september': 'szeptember',
            'october': 'október',
            'november': 'november',
            'december': 'december'
        },
        'kk-KZ': {
            'january': 'Қаңтар',
            'february': 'Ақпан',
            'march': 'Наурыз',
            'april': 'Сәуір',
            'may': 'Мамыр',
            'june': 'Маусым',
            'july': 'Шілде',
            'august': 'Тамыз',
            'september': 'Қыркүйек',
            'october': 'Қазан',
            'november': 'Қараша',
            'december': 'Желтоқсан'
        },
        'lt-LT': {
            'january': 'Sausis',
            'february': 'Vasaris',
            'march': 'Kovas',
            'april': 'Balandis',
            'may': 'Gegužė',
            'june': 'Birželis',
            'july': 'Liepa',
            'august': 'Rugpjūtis',
            'september': 'Rugsėjis',
            'october': 'Spalis',
            'november': 'Lapkritis',
            'december': 'Gruodis'
        },
        'pl-PL': {
            'january': 'Styczeń',
            'february': 'Luty',
            'march': 'Marzec',
            'april': 'Kwiecień',
            'may': 'Maj',
            'june': 'Czerwiec',
            'july': 'Lipiec',
            'august': 'Sierpień',
            'september': 'Wrzesień',
            'october': 'Październik',
            'november': 'Listopad',
            'december': 'Grudzień'
        },
        'ro-RO': {
            'january': 'ianuarie',
            'february': 'februarie',
            'march': 'martie',
            'april': 'aprilie',
            'may': 'mai',
            'june': 'iunie',
            'july': 'iulie',
            'august': 'august',
            'september': 'septembrie',
            'october': 'octombrie',
            'november': 'noiembrie',
            'december': 'decembrie'
        },
        'sr-Latn-CS': {
            'The first number to add': 'Prvi sabirak',
            'The second number to add': 'Drugi sabirak',
            'january': 'Januar',
            'february': 'Februar',
            'march': 'Mart',
            'april': 'April',
            'may': 'Maj',
            'june': 'Jun',
            'july': 'Jul',
            'august': 'Avgust',
            'september': 'Septembar',
            'october': 'Oktobar',
            'november': 'Novembar',
            'december': 'Decembar'
        },
        'ru-RU': {
            'january': 'Январь',
            'february': 'Февраль',
            'march': 'Март',
            'april': 'Апрель',
            'may': 'Май',
            'june': 'Июнь',
            'july': 'Июль',
            'august': 'Август',
            'september': 'Сентябрь',
            'october': 'Октябрь',
            'november': 'Ноябрь',
            'december': 'Декабрь'
        },
        'sl-SI': {
            'january': 'januar',
            'february': 'februar',
            'march': 'marec',
            'april': 'april',
            'may': 'maj',
            'june': 'junij',
            'july': 'julij',
            'august': 'avgust',
            'september': 'september',
            'october': 'oktober',
            'november': 'november',
            'december': 'december'
        },
        'sk-SK': {
            'january': 'Január',
            'february': 'Február',
            'march': 'Marec',
            'april': 'Apríl',
            'may': 'Máj',
            'june': 'Jún',
            'july': 'Júl',
            'august': 'August',
            'september': 'September',
            'october': 'Október',
            'november': 'November',
            'december': 'December'
        },
        'tr-TR': {
            'january': 'ocak',
            'february': 'şubat',
            'march': 'mart',
            'april': 'nisan',
            'may': 'mayıs',
            'june': 'haziran',
            'july': 'temmuz',
            'august': 'ağustos',
            'september': 'eylül',
            'october': 'ekim',
            'november': 'kasım',
            'december': 'aralık'
        },
        'uk-UA': {
            'january': 'Січень',
            'february': 'Лютий',
            'march': 'Березень',
            'april': 'Квітень',
            'may': 'Травень',
            'june': 'Червень',
            'july': 'Липень',
            'august': 'Серпень',
            'september': 'Вересень',
            'october': 'Жовтень',
            'november': 'Листопад',
            'december': 'Грудень'
        }
    }
}